# Concatinate & Split Python Numpy Array

In [2]:
import numpy as np

In [3]:
array_1 = np.arange(1,17).reshape(4,4)
print(array_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
array_2 = np.arange(17,33).reshape(4,4)
print(array_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


# Note:
If you want to merge both <b> list </b> we can do the same using <b> '+' operator. </b>. But when comes to <b> array </b> we need to use the <b> Concate </b> function since if we use <b> + Operator</b> then the <b>values will add up insted of merge</b>

In [5]:
list1 = [1,2,3]
list2 = [4,5,6]


In [6]:
list3 = list1 + list2

In [7]:
list3

[1, 2, 3, 4, 5, 6]

In [8]:
array_3 = array_1 + array_2

In [9]:
array_3

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [10]:
#concatenate Column wise
np.concatenate((array_1,array_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [11]:
#concatenate Row wise (1st Method)
np.concatenate((array_1,array_2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
#concatenate Row wise (2nd Method) using vstack function : 
#Vstack helps row to concatenate Vertically
np.vstack((array_1,array_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [13]:
#concatenate Row wise (3rd Method) using hstack function : 
#hstack helps row to concatenate Horizontally
np.hstack((array_1,array_2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [14]:
#Multiple Rows

np.hstack((array_1,array_2,array_3))

array([[ 1,  2,  3,  4, 17, 18, 19, 20, 18, 20, 22, 24],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 26, 28, 30, 32],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 34, 36, 38, 40],
       [13, 14, 15, 16, 29, 30, 31, 32, 42, 44, 46, 48]])