# Mathematical Function

In [3]:
import numpy as np

In [4]:
#if you want to change 1D array to 3D array
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

In [5]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#addition (1st Method)
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
#addition (2nd Method)
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
#substraction (1st Method)
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
#substraction (2nd Method)
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
#Divide (1st Method)
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#Divide (2nd method)
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#Multiply (1st Method)
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
#Multiply (2nd method)
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
#Maximun value from array
arr1.max()

9

In [15]:
# so 9 is the highest value and its index position is 8
arr1.argmax()

8

In [16]:
#0 is the column so here for the 1st row max value is 7 ; for 2nd it is 8 and for 3rd it is 9
arr1.max(axis=0)

array([7, 8, 9])

In [17]:
#1 is the row so here for the 1st row max value is 3 ; for 2nd it is 6 and for 3rd it is 9
arr1.max(axis=1)

array([3, 6, 9])

In [18]:
# Min
arr1.min()

1

In [19]:
arr1.argmin()

0

In [20]:
# here 1 is the min value for col 1 ; 2 is the min for col 2 ; 3 is the min value for col 3
arr1.min(axis=0)

array([1, 2, 3])

In [21]:
# here 1 is the min value for row 1 ; 4 is the min for row 2 ; 7 is the min value for row 3
arr1.min(axis=1)

array([1, 4, 7])

In [22]:
#sum (col wise)
np.sum(arr1, axis=0)

array([12, 15, 18])

In [23]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#sum (row wise)
np.sum(arr1, axis=1)

array([ 6, 15, 24])

In [25]:
#average
np.mean(arr1)

5.0

In [26]:
#sq.root individually
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [27]:
# standrad diviation
np.std(arr1)

2.581988897471611

In [28]:
#Exponent
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [29]:
#log
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])