# NUMPY : 

NUM Stands for numeric & Py stands for Python
So we perform numerical calcualtion using Python using Numpy Library

1D array <br/>
2D array <br/>
3D array <br/>
Images is used in numerical form to view


In [2]:
import numpy as np

In [3]:
#create 1D array : ONE LIST
One_D = np.array([1,2,3,4])
print(One_D)

[1 2 3 4]


In [4]:
type(One_D)

numpy.ndarray

In [5]:
# Check 1d, 2D, multi dimentional array
One_D.ndim

1

In [6]:
#create 2D array : LIST WITHIN LIST
Two_D = np.array([[1,2,3,4],[1,2,3,4]])
print(Two_D)

[[1 2 3 4]
 [1 2 3 4]]


In [7]:
Two_D.ndim

2

In [8]:
#how many element are there/ size of the array
Two_D.size

8

In [9]:
#shape of the array. no of rows & columns (1st : Row i.e 2 | 2nd Coulumn  i.e 4)
Two_D.shape

(2, 4)

In [10]:
#check Datatypes
Two_D.dtype

dtype('int32')