# Numpy Function

In [1]:
import numpy as np

# arrange

In [3]:
#np.arange(star, end , steps)
Function1 = np.arange(1,13)
print(Function1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
Function2 = np.arange(1,13,2)
print(Function2)

[ 1  3  5  7  9 11]


# linespace

In [5]:
np.linspace(1,5 ,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
np.linspace(1,5 ,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [7]:
np.linspace(1,5 ,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape

In [8]:
#convert id array to 2d
Reshape1 =Function1.reshape(2,6)
print(Reshape1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
Reshape2 = Function1.reshape(3,4)
print(Reshape2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
 #convert id array to 3d
Reshape3 = Function1.reshape(2,3,2)
print(Reshape3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
Reshape2 = Function1.reshape(3,4)
print(Reshape2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
 #convert id array to 3d
Reshape3 = Function1.reshape(2,3,2)
print(Reshape3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel

In [13]:
#convert multi dimentional array to 1D
Reshape1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten

In [14]:
#convert multi dimentional array to 1D
Reshape1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose

In [15]:
#convert row to column
Reshape1.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [16]:
Reshape2.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])