# Matrix

In [1]:
import numpy as np

In [2]:
matrix_1D = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1D)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
matrix_1D_Type1 = np.ones(5)
print(matrix_1D_Type1)

[1. 1. 1. 1. 1.]


In [5]:
#ones matrix create by default float
matrix_1D_Type1.dtype

dtype('float64')

In [6]:
#converting float into integer
matrix_1D_Type3 = np.ones((4,5), dtype = int)
print(matrix_1D_Type3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
#Zeros Matrix
matrix_0 = np.zeros((4,5))
print(matrix_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#change data type from float to Boolean

matrix_0_Type1 = np.zeros((4,5), dtype = bool)
print(matrix_0_Type1)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [9]:
#change data type from float to string

matrix_0_Type2 = np.zeros((4,5), dtype = str)
print(matrix_0_Type2)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [10]:
#creating empty matrix. Empty matrix can have randam value
empty_matrix = np.empty((4,4))
print(empty_matrix)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 1.37961777e-306 7.56599807e-307]]
