# Random

In [2]:
#If we need value from 0-1 then we can use Random function

In [3]:
import numpy as np
import random

In [4]:
np.random.random()

0.9559712690818619

In [5]:
np.random.random((3,3))

array([[0.56927042, 0.22287993, 0.61542733],
       [0.16792908, 0.61724238, 0.53418768],
       [0.29048519, 0.64005965, 0.56191674]])

In [6]:
np.random.randint(1,4)

1

In [7]:
np.random.randint(1,4, (4,4))

array([[2, 2, 1, 1],
       [3, 2, 2, 2],
       [3, 1, 3, 3],
       [2, 2, 3, 3]])

In [8]:
#seed 
2**32-1

4294967295

In [9]:
np.random.rand(3,3)

array([[0.90536973, 0.50288781, 0.55648593],
       [0.48548381, 0.05340283, 0.40163064],
       [0.59393157, 0.51511194, 0.34683497]])

In [10]:
#neg & pos
np.random.randn(3,3)

array([[-0.39528604,  0.94019524, -0.03494514],
       [ 0.29920635,  2.22096152, -0.00252666],
       [-1.46209709,  0.32027231, -0.2813751 ]])

In [11]:
x = [1,2,3,4]
np.random.choice(x)

4

In [12]:
np.random.choice(x)

4

# For Loop

In [13]:
#for loop
for i in range(20):
    print(np.random.choice(x))

4
4
4
4
2
3
1
2
2
3
1
2
4
3
3
1
3
3
3
2


In [14]:
x

[1, 2, 3, 4]

In [15]:
#permutation
np.random.permutation(x)

array([3, 1, 2, 4])

In [16]:
np.random.permutation(x)

array([3, 2, 4, 1])