# Split array

In [10]:
import numpy as np

In [11]:
array_1 = np.arange(1,17).reshape(4,4)
print(array_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
array_2 = np.arange(17,33).reshape(4,4)
print(array_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [13]:
List = np.split(array_1,2)

In [14]:
print(List)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [15]:
List[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
#Split array Row wise
np.split(array_1, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [17]:
d1 = np.array([4,7,1,3,9])